### PR TITLE
Updated NSS dependency

### PR DESCRIPTION
**Pull request by mark-in**

### CODE REVIEW

**Comment by MeisterP** [comment]
Does the build fail with >=dev-libs/nss-3.17.1 ?
I keep the ebuild in sync with the [www-client/firefox-31.7.0.ebuild](https://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/www-client/firefox/firefox-31.7.0.ebuild?revision=1.5&view=markup) which still uses >=dev-libs/nss-3.17.1 (see line 56)

**Comment by mark-in** [comment]
Yes it is.
```
configure:15063: checking for nss-config
configure:15098: checking for NSS - version >= 3.19.1
configure: error: you don't have NSS installed or your version is too old
```
I think that TB is now require new NSS in order to fix the [Logjam attack](https://weakdh.org/): [Tor Browser 4.5.2 is released](https://blog.torproject.org/blog/tor-browser-452-released).
It is worth mentioning that a Firefox version is still the same.

**Comment by MeisterP** [comment]
Yes, indeed. https://gitweb.torproject.org/tor-browser.git/commit/?h=tor-browser-31.7.0esr-4.5-2&id=c49bb400a7e2afc5650257c24ca132aee68365de
Thanks for the report and the fix.

**Comment by mark-in** [comment]
I've checked this out. According to [release notes for NSS 3.19.1](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/NSS_3.19.1_release_notes):
> The minimum strength of keys that libssl will accept for finite field algorithms (RSA, Diffie-Hellman, and DSA) have been increased to 1023 bits (bug 1138554).

**Pull request merged**
